# Generated by Django 4.1.13 on 2023-12-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usercertification_certification_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usercertification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usercontact',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usereducation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userinterest',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userlanguage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userproject',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userskill',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usersocialmedia',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userworkexperience',
            table=None,
        ),
    ]
