# Generated by Django 5.0 on 2023-12-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_rename_name_tag_tag_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
