# Generated by Django 4.1.13 on 2023-12-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='content',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
