# Generated by Django 4.1.13 on 2023-12-29 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_alter_blogcontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blogapp.blogcontent'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag'], name='blogapp_tag_tag_339689_idx'),
        ),
    ]
