# Generated by Django 4.1.13 on 2023-12-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_blog_content_tag_blogapp_tag_tag_339689_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
