# Generated by Django 4.1.13 on 2024-01-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_remove_blog_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='thumbnail/'),
        ),
    ]
