# Generated by Django 4.1.13 on 2024-01-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_school_name_usereducation_school_clg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='proficiency_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('fluent', 'Fluent'), ('native', 'Native')], default='intermediate', max_length=50),
        ),
    ]
