# Generated by Django 4.1.13 on 2024-01-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertification',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercontact',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='language_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='project_link',
            field=models.URLField(default=''),
        ),
    ]
